before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  -
    id: headless
    binary: nm-install
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - linux_amd64

archives:
  - format: binary
    name_template: '{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}'

release:
  target_commitish: "{{ .Commit }}"

