name: Release nm-install
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:

  release-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git tag ${{ inputs.version }}
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
